site_name: Documentation Template
site_description: Template for deploying docs using GitHub Pages and mkdocs.
site_author: Kevin Kandlbinder
site_url: https://doctemplate.kevink.dev

repo_name: Unkn0wnCat/doctemplate
repo_url: https://github.com/Unkn0wnCat/doctemplate

copyright: CC-BY-4.0 Kevin Kandlbinder

docs_dir: docs

nav:
  - Home: 
    - index.md
    - demo.md
  - 'External Link':
    - 'External Link': 'https://kevink.dev/'

theme:
  name: material
  language: de
  palette:
    primary: deep orange
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs

plugins:
  - search
    
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Unkn0wnCat
      
markdown_extensions:
  - abbr
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  - toc:
      permalink: true